package org.gs4tr.projectdirector.ws.service.services.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2016-05-25T10:39:22.011+03:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", name = "DocumentServicePortType")
@XmlSeeAlso({ObjectFactory.class, org.gs4tr.projectdirector.model.dto.ObjectFactory.class, org.w3._2005._05.xmlmime.ObjectFactory.class})
public interface DocumentServicePortType {

    @WebMethod(action = "urn:cancelDocument")
    @Action(input = "urn:cancelDocument", output = "urn:cancelDocumentResponse")
    @RequestWrapper(localName = "cancelDocument", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.CancelDocument")
    @ResponseWrapper(localName = "cancelDocumentResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.CancelDocumentResponse")
    @WebResult(name = "return", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
    public java.lang.String cancelDocument(
        @WebParam(name = "documentTicket", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        org.gs4tr.projectdirector.model.dto.DocumentTicket documentTicket
    );

    @WebMethod(action = "urn:submitDocumentWithBinaryResource")
    @Action(input = "urn:submitDocumentWithBinaryResource", output = "urn:submitDocumentWithBinaryResourceResponse")
    @RequestWrapper(localName = "submitDocumentWithBinaryResource", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.SubmitDocumentWithBinaryResource")
    @ResponseWrapper(localName = "submitDocumentWithBinaryResourceResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.SubmitDocumentWithBinaryResourceResponse")
    @WebResult(name = "return", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
    public org.gs4tr.projectdirector.model.dto.DocumentTicket submitDocumentWithBinaryResource(
        @WebParam(name = "documentInfo", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        org.gs4tr.projectdirector.model.dto.DocumentInfo documentInfo,
        @WebParam(name = "resourceInfo", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        org.gs4tr.projectdirector.model.dto.ResourceInfo resourceInfo,
        @WebParam(name = "data", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        org.w3._2005._05.xmlmime.Base64Binary data
    );

    @WebMethod(action = "urn:findByTicket")
    @Action(input = "urn:findByTicket", output = "urn:findByTicketResponse")
    @RequestWrapper(localName = "findByTicket", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.FindDocumentByTicket")
    @ResponseWrapper(localName = "findByTicketResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.FindDocumentByTicketResponse")
    @WebResult(name = "return", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
    public org.gs4tr.projectdirector.model.dto.Document findByTicket(
        @WebParam(name = "ticket", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        java.lang.String ticket
    );

    @WebMethod(action = "urn:submitDocumentWithTextResource")
    @Action(input = "urn:submitDocumentWithTextResource", output = "urn:submitDocumentWithTextResourceResponse")
    @RequestWrapper(localName = "submitDocumentWithTextResource", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.SubmitDocumentWithTextResource")
    @ResponseWrapper(localName = "submitDocumentWithTextResourceResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.SubmitDocumentWithTextResourceResponse")
    @WebResult(name = "return", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
    public org.gs4tr.projectdirector.model.dto.DocumentTicket submitDocumentWithTextResource(
        @WebParam(name = "documentInfo", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        org.gs4tr.projectdirector.model.dto.DocumentInfo documentInfo,
        @WebParam(name = "resourceInfo", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        org.gs4tr.projectdirector.model.dto.ResourceInfo resourceInfo,
        @WebParam(name = "data", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        java.lang.String data
    );

    /**
     * Deprecated since 4.5.0
     */
    @WebMethod(action = "urn:search")
    @Action(input = "urn:search", output = "urn:searchResponse")
    @RequestWrapper(localName = "search", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.SearchDocument")
    @ResponseWrapper(localName = "searchResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.SearchDocumentResponse")
    @WebResult(name = "return", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
    public org.gs4tr.projectdirector.model.dto.DocumentPagedList search(
        @WebParam(name = "command", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        org.gs4tr.projectdirector.model.dto.DocumentSearchRequest command,
        @WebParam(name = "info", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        org.gs4tr.projectdirector.model.dto.PagedListInfo info
    );
}
