
package org.gs4tr.projectdirector.ws.service.services.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.gs4tr.projectdirector.model.dto.xsd.Document;
import org.gs4tr.projectdirector.model.dto.xsd.DocumentInfo;
import org.gs4tr.projectdirector.model.dto.xsd.DocumentPagedList;
import org.gs4tr.projectdirector.model.dto.xsd.DocumentSearchRequest;
import org.gs4tr.projectdirector.model.dto.xsd.DocumentTicket;
import org.gs4tr.projectdirector.model.dto.xsd.PagedListInfo;
import org.gs4tr.projectdirector.model.dto.xsd.ResourceInfo;
import org.w3._2005._05.xmlmime.Base64Binary;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DocumentServicePortType", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
@XmlSeeAlso({
    org.gs4tr.projectdirector.model.dto.xsd.ObjectFactory.class,
    org.gs4tr.projectdirector.ws.service.services.impl.ObjectFactory.class,
    org.w3._2005._05.xmlmime.ObjectFactory.class
})
public interface DocumentServicePortType {


    /**
     * 
     * @param ticket
     * @return
     *     returns org.gs4tr.projectdirector.model.dto.xsd.Document
     */
    @WebMethod(action = "urn:findByTicket")
    @WebResult(targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
    @RequestWrapper(localName = "findByTicket", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.FindDocumentByTicket")
    @ResponseWrapper(localName = "findByTicketResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.FindDocumentByTicketResponse")
    public Document findByTicket(
        @WebParam(name = "ticket", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        String ticket);

    /**
     * 
     * @param resourceInfo
     * @param data
     * @param documentInfo
     * @return
     *     returns org.gs4tr.projectdirector.model.dto.xsd.DocumentTicket
     */
    @WebMethod(action = "urn:submitDocumentWithTextResource")
    @WebResult(targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
    @RequestWrapper(localName = "submitDocumentWithTextResource", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.SubmitDocumentWithTextResource")
    @ResponseWrapper(localName = "submitDocumentWithTextResourceResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.SubmitDocumentWithTextResourceResponse")
    public DocumentTicket submitDocumentWithTextResource(
        @WebParam(name = "documentInfo", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        DocumentInfo documentInfo,
        @WebParam(name = "resourceInfo", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        ResourceInfo resourceInfo,
        @WebParam(name = "data", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        String data);

    /**
     * 
     * @param resourceInfo
     * @param data
     * @param documentInfo
     * @return
     *     returns org.gs4tr.projectdirector.model.dto.xsd.DocumentTicket
     */
    @WebMethod(action = "urn:submitDocumentWithBinaryResource")
    @WebResult(targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
    @RequestWrapper(localName = "submitDocumentWithBinaryResource", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.SubmitDocumentWithBinaryResource")
    @ResponseWrapper(localName = "submitDocumentWithBinaryResourceResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.SubmitDocumentWithBinaryResourceResponse")
    public DocumentTicket submitDocumentWithBinaryResource(
        @WebParam(name = "documentInfo", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        DocumentInfo documentInfo,
        @WebParam(name = "resourceInfo", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        ResourceInfo resourceInfo,
        @WebParam(name = "data", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        Base64Binary data);

    /**
     * 
     * @param documentTicket
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:cancelDocument")
    @WebResult(targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
    @RequestWrapper(localName = "cancelDocument", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.CancelDocument")
    @ResponseWrapper(localName = "cancelDocumentResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.CancelDocumentResponse")
    public String cancelDocument(
        @WebParam(name = "documentTicket", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        DocumentTicket documentTicket);

    /**
     * Deprecated since 4.5.0
     * 
     * @param command
     * @param info
     * @return
     *     returns org.gs4tr.projectdirector.model.dto.xsd.DocumentPagedList
     */
    @WebMethod(action = "urn:search")
    @WebResult(targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
    @RequestWrapper(localName = "search", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.SearchDocument")
    @ResponseWrapper(localName = "searchResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.SearchDocumentResponse")
    public DocumentPagedList search(
        @WebParam(name = "command", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        DocumentSearchRequest command,
        @WebParam(name = "info", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        PagedListInfo info);

}
