
package org.gs4tr.projectdirector.ws.service.services.impl;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.4-b01 Generated
 * source version: 2.2
 * 
 */
@WebServiceClient(name = "ProjectService_4130", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
public class ProjectService4130 extends Service {

	private static URL PROJECTSERVICE4130_WSDL_LOCATION;
	private static WebServiceException PROJECTSERVICE4130_EXCEPTION;
	private final static QName PROJECTSERVICE4130_QNAME = new QName(
			"http://impl.services.service.ws.projectdirector.gs4tr.org", "ProjectService_4130");

	public ProjectService4130() {
		super(__getWsdlLocation(), PROJECTSERVICE4130_QNAME);
	}

	public ProjectService4130(WebServiceFeature... features) {
		super(__getWsdlLocation(), PROJECTSERVICE4130_QNAME, features);
	}

	public ProjectService4130(URL wsdlLocation) {
		super(wsdlLocation, PROJECTSERVICE4130_QNAME);
		PROJECTSERVICE4130_WSDL_LOCATION = wsdlLocation;
		PROJECTSERVICE4130_EXCEPTION = null;
	}

	public ProjectService4130(URL wsdlLocation, WebServiceFeature... features) {
		super(wsdlLocation, PROJECTSERVICE4130_QNAME, features);
		PROJECTSERVICE4130_WSDL_LOCATION = wsdlLocation;
		PROJECTSERVICE4130_EXCEPTION = null;
	}

	public ProjectService4130(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
		PROJECTSERVICE4130_WSDL_LOCATION = wsdlLocation;
		PROJECTSERVICE4130_EXCEPTION = null;
	}

	public ProjectService4130(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
		super(wsdlLocation, serviceName, features);
		PROJECTSERVICE4130_WSDL_LOCATION = wsdlLocation;
		PROJECTSERVICE4130_EXCEPTION = null;
	}

	/**
	 * 
	 * @return returns ProjectServicePortType
	 */
	@WebEndpoint(name = "ProjectServiceHttpSoap11Endpoint")
	public ProjectServicePortType getProjectServiceHttpSoap11Endpoint() {
		return super.getPort(new QName("http://impl.services.service.ws.projectdirector.gs4tr.org",
				"ProjectServiceHttpSoap11Endpoint"), ProjectServicePortType.class);
	}

	/**
	 * 
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
	 *            on the proxy. Supported features not in the
	 *            <code>features</code> parameter will have their default
	 *            values.
	 * @return returns ProjectServicePortType
	 */
	@WebEndpoint(name = "ProjectServiceHttpSoap11Endpoint")
	public ProjectServicePortType getProjectServiceHttpSoap11Endpoint(WebServiceFeature... features) {
		return super.getPort(new QName("http://impl.services.service.ws.projectdirector.gs4tr.org",
				"ProjectServiceHttpSoap11Endpoint"), ProjectServicePortType.class, features);
	}

	private static URL __getWsdlLocation() {
		if (PROJECTSERVICE4130_EXCEPTION != null) {
			throw PROJECTSERVICE4130_EXCEPTION;
		}
		return PROJECTSERVICE4130_WSDL_LOCATION;
	}

}
