
package org.gs4tr.projectdirector.ws.service.services.impl;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.4-b01 Generated
 * source version: 2.2
 * 
 */
@WebServiceClient(name = "ProjectService_4180", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
public class ProjectService4180 extends Service {

	private static URL PROJECTSERVICE4180_WSDL_LOCATION;
	private static WebServiceException PROJECTSERVICE4180_EXCEPTION;
	private final static QName PROJECTSERVICE4180_QNAME = new QName(
			"http://impl.services.service.ws.projectdirector.gs4tr.org", "ProjectService_4180");

	public ProjectService4180() {
		super(__getWsdlLocation(), PROJECTSERVICE4180_QNAME);
	}

	public ProjectService4180(WebServiceFeature... features) {
		super(__getWsdlLocation(), PROJECTSERVICE4180_QNAME, features);
	}

	public ProjectService4180(URL wsdlLocation) {
		super(wsdlLocation, PROJECTSERVICE4180_QNAME);
		PROJECTSERVICE4180_WSDL_LOCATION = wsdlLocation;
		PROJECTSERVICE4180_EXCEPTION = null;
	}

	public ProjectService4180(URL wsdlLocation, WebServiceFeature... features) {
		super(wsdlLocation, PROJECTSERVICE4180_QNAME, features);
		PROJECTSERVICE4180_WSDL_LOCATION = wsdlLocation;
		PROJECTSERVICE4180_EXCEPTION = null;
	}

	public ProjectService4180(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
		PROJECTSERVICE4180_WSDL_LOCATION = wsdlLocation;
		PROJECTSERVICE4180_EXCEPTION = null;
	}

	public ProjectService4180(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
		super(wsdlLocation, serviceName, features);
		PROJECTSERVICE4180_WSDL_LOCATION = wsdlLocation;
		PROJECTSERVICE4180_EXCEPTION = null;
	}

	/**
	 * 
	 * @return returns ProjectServicePortType
	 */
	@WebEndpoint(name = "ProjectServiceHttpSoap11Endpoint")
	public ProjectServicePortType getProjectServiceHttpSoap11Endpoint() {
		return super.getPort(new QName("http://impl.services.service.ws.projectdirector.gs4tr.org",
				"ProjectServiceHttpSoap11Endpoint"), ProjectServicePortType.class);
	}

	/**
	 * 
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
	 *            on the proxy. Supported features not in the
	 *            <code>features</code> parameter will have their default
	 *            values.
	 * @return returns ProjectServicePortType
	 */
	@WebEndpoint(name = "ProjectServiceHttpSoap11Endpoint")
	public ProjectServicePortType getProjectServiceHttpSoap11Endpoint(WebServiceFeature... features) {
		return super.getPort(new QName("http://impl.services.service.ws.projectdirector.gs4tr.org",
				"ProjectServiceHttpSoap11Endpoint"), ProjectServicePortType.class, features);
	}

	private static URL __getWsdlLocation() {
		if (PROJECTSERVICE4180_EXCEPTION != null) {
			throw PROJECTSERVICE4180_EXCEPTION;
		}
		return PROJECTSERVICE4180_WSDL_LOCATION;
	}

}
