
package org.gs4tr.projectdirector.ws.service.services.impl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.gs4tr.projectdirector.model.dto.xsd.DownloadCollateralResult;
import org.gs4tr.projectdirector.model.dto.xsd.PagedListInfo;
import org.gs4tr.projectdirector.model.dto.xsd.ResourceInfo;
import org.gs4tr.projectdirector.model.dto.xsd.Submission;
import org.gs4tr.projectdirector.model.dto.xsd.SubmissionInfo;
import org.gs4tr.projectdirector.model.dto.xsd.SubmissionPagedList;
import org.gs4tr.projectdirector.model.dto.xsd.SubmissionSearchModelPagedList;
import org.gs4tr.projectdirector.model.dto.xsd.SubmissionSearchRequest;
import org.w3._2005._05.xmlmime.Base64Binary;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SubmissionServicePortType", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
@XmlSeeAlso({
    org.gs4tr.projectdirector.model.dto.xsd.ObjectFactory.class,
    org.gs4tr.projectdirector.ws.service.services.impl.ObjectFactory.class,
    org.w3._2005._05.xmlmime.ObjectFactory.class
})
public interface SubmissionServicePortType {


    /**
     * 
     * @param referenceDocumentName
     * @param submissionTicket
     * @param encoding
     * @param referenceText
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:addReferenceAsText")
    @WebResult(targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
    @RequestWrapper(localName = "addReferenceAsText", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.AddReferenceAsText")
    @ResponseWrapper(localName = "addReferenceAsTextResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.AddReferenceAsTextResponse")
    public String addReferenceAsText(
        @WebParam(name = "referenceText", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        String referenceText,
        @WebParam(name = "referenceDocumentName", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        String referenceDocumentName,
        @WebParam(name = "encoding", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        String encoding,
        @WebParam(name = "submissionTicket", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        String submissionTicket);

    /**
     * 
     * @param submissionTicket
     * @param username
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:addSubmitter")
    @WebResult(targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
    @RequestWrapper(localName = "addSubmitter", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.AddSubmitter")
    @ResponseWrapper(localName = "addSubmitterResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.AddSubmitterResponse")
    public String addSubmitter(
        @WebParam(name = "submissionTicket", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        String submissionTicket,
        @WebParam(name = "username", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        String username);

    /**
     * 
     * @param submissionId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:cancelSubmission")
    @WebResult(targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
    @RequestWrapper(localName = "cancelSubmission", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.CancelSubmission")
    @ResponseWrapper(localName = "cancelSubmissionResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.CancelSubmissionResponse")
    public String cancelSubmission(
        @WebParam(name = "submissionId", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        String submissionId);

    /**
     * 
     * @param comment
     * @param submissionId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:cancelSubmissionWithComment")
    @WebResult(targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
    @RequestWrapper(localName = "cancelSubmissionWithComment", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.CancelSubmissionWithComment")
    @ResponseWrapper(localName = "cancelSubmissionWithCommentResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.CancelSubmissionWithCommentResponse")
    public String cancelSubmissionWithComment(
        @WebParam(name = "submissionId", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        String submissionId,
        @WebParam(name = "comment", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        String comment);

    /**
     * 
     * @param uuid
     * @return
     *     returns org.gs4tr.projectdirector.model.dto.xsd.DownloadCollateralResult
     */
    @WebMethod(action = "urn:checkDownloadDeliverableCollateral")
    @WebResult(targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
    @RequestWrapper(localName = "checkDownloadDeliverableCollateral", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.CheckDownloadDeliverableCollateral")
    @ResponseWrapper(localName = "checkDownloadDeliverableCollateralResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.CheckDownloadDeliverableCollateralResponse")
    public DownloadCollateralResult checkDownloadDeliverableCollateral(
        @WebParam(name = "uuid", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        String uuid);

    /**
     * 
     * @param submissionTicket
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:downloadDeliverableCollateralBySubmissionTicket")
    @WebResult(targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
    @RequestWrapper(localName = "downloadDeliverableCollateralBySubmissionTicket", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.DownloadDeliverableCollateralBySubmissionTicket")
    @ResponseWrapper(localName = "downloadDeliverableCollateralBySubmissionTicketResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.DownloadDeliverableCollateralBySubmissionTicketResponse")
    public String downloadDeliverableCollateralBySubmissionTicket(
        @WebParam(name = "submissionTicket", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        String submissionTicket);

    /**
     * 
     * @param submissionTicket
     * @param targetLanguages
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:downloadDeliverableCollateralBySubmissionTicketAndTargetLanguages")
    @WebResult(targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
    @RequestWrapper(localName = "downloadDeliverableCollateralBySubmissionTicketAndTargetLanguages", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.DownloadDeliverableCollateralBySubmissionTicketAndTargetLanguages")
    @ResponseWrapper(localName = "downloadDeliverableCollateralBySubmissionTicketAndTargetLanguagesResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.DownloadDeliverableCollateralBySubmissionTicketAndTargetLanguagesResponse")
    public String downloadDeliverableCollateralBySubmissionTicketAndTargetLanguages(
        @WebParam(name = "submissionTicket", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        String submissionTicket,
        @WebParam(name = "targetLanguages", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        List<String> targetLanguages);

    /**
     * 
     * @param submissionId
     * @return
     *     returns org.gs4tr.projectdirector.model.dto.xsd.Submission
     */
    @WebMethod(action = "urn:findById")
    @WebResult(targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
    @RequestWrapper(localName = "findById", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.FindSubmissionById")
    @ResponseWrapper(localName = "findByIdResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.FindSubmissionByIdResponse")
    public Submission findById(
        @WebParam(name = "submissionId", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        long submissionId);

    /**
     * 
     * @param ticket
     * @return
     *     returns org.gs4tr.projectdirector.model.dto.xsd.Submission
     */
    @WebMethod(action = "urn:findByTicket")
    @WebResult(targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
    @RequestWrapper(localName = "findByTicket", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.FindSubmissionByTicket")
    @ResponseWrapper(localName = "findByTicketResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.FindSubmissionByTicketResponse")
    public Submission findByTicket(
        @WebParam(name = "ticket", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        String ticket);

    /**
     * 
     * @param projectShortCode
     * @return
     *     returns java.util.List<org.gs4tr.projectdirector.model.dto.xsd.Submission>
     */
    @WebMethod(action = "urn:findCreatingSubmissionsByProjectShortCode")
    @WebResult(targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
    @RequestWrapper(localName = "findCreatingSubmissionsByProjectShortCode", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.FindCreatingSubmissionsByProjectShortCode")
    @ResponseWrapper(localName = "findCreatingSubmissionsByProjectShortCodeResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.FindCreatingSubmissionsByProjectShortCodeResponse")
    public List<Submission> findCreatingSubmissionsByProjectShortCode(
        @WebParam(name = "projectShortCode", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        String projectShortCode);

    /**
     * Deprecated since 4.5.0
     * 
     * @param command
     * @param info
     * @return
     *     returns org.gs4tr.projectdirector.model.dto.xsd.SubmissionPagedList
     */
    @WebMethod(action = "urn:search")
    @WebResult(targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
    @RequestWrapper(localName = "search", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.SearchSubmission")
    @ResponseWrapper(localName = "searchResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.SearchSubmissionResponse")
    public SubmissionPagedList search(
        @WebParam(name = "command", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        SubmissionSearchRequest command,
        @WebParam(name = "info", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        PagedListInfo info);

    /**
     * Deprecated since 4.5.0
     * 
     * @param submissionSearchRequest
     * @param info
     * @return
     *     returns org.gs4tr.projectdirector.model.dto.xsd.SubmissionSearchModelPagedList
     */
    @WebMethod(action = "urn:searchSubmissions")
    @WebResult(targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
    @RequestWrapper(localName = "searchSubmissions", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.SearchSubmissions")
    @ResponseWrapper(localName = "searchSubmissionsResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.SearchSubmissionsResponse")
    public SubmissionSearchModelPagedList searchSubmissions(
        @WebParam(name = "submissionSearchRequest", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        SubmissionSearchRequest submissionSearchRequest,
        @WebParam(name = "info", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        PagedListInfo info);

    /**
     * 
     * @param submissionTicket
     * @param username
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:addOwner")
    @WebResult(targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
    @RequestWrapper(localName = "addOwner", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.AddOwner")
    @ResponseWrapper(localName = "addOwnerResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.AddOwnerResponse")
    public String addOwner(
        @WebParam(name = "submissionTicket", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        String submissionTicket,
        @WebParam(name = "username", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        String username);

    /**
     * 
     * @param submissionInfo
     * @param submissionId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:startSingleBatchSubmission")
    @WebResult(targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
    @RequestWrapper(localName = "startSingleBatchSubmission", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.StartSingleBatchSubmission")
    @ResponseWrapper(localName = "startSingleBatchSubmissionResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.StartSingleBatchSubmissionResponse")
    public String startSingleBatchSubmission(
        @WebParam(name = "submissionId", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        String submissionId,
        @WebParam(name = "submissionInfo", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        SubmissionInfo submissionInfo);

    /**
     * 
     * @param submissionInfo
     * @param submissionId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:startSubmission")
    @WebResult(targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
    @RequestWrapper(localName = "startSubmission", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.StartSubmission")
    @ResponseWrapper(localName = "startSubmissionResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.StartSubmissionResponse")
    public String startSubmission(
        @WebParam(name = "submissionId", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        String submissionId,
        @WebParam(name = "submissionInfo", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        SubmissionInfo submissionInfo);

    /**
     * 
     * @param resourceInfo
     * @param data
     * @param submissionId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:uploadReference")
    @WebResult(targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
    @RequestWrapper(localName = "uploadReference", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.UploadReference")
    @ResponseWrapper(localName = "uploadReferenceResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.UploadReferenceResponse")
    public String uploadReference(
        @WebParam(name = "submissionId", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        String submissionId,
        @WebParam(name = "resourceInfo", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        ResourceInfo resourceInfo,
        @WebParam(name = "data", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        Base64Binary data);

}
