
package org.gs4tr.projectdirector.ws.service.services.impl;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TargetService_4130", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
public class TargetService4130
    extends Service
{

    private static URL TARGETSERVICE4130_WSDL_LOCATION;
    private static WebServiceException TARGETSERVICE4130_EXCEPTION;
    private final static QName TARGETSERVICE4130_QNAME = new QName("http://impl.services.service.ws.projectdirector.gs4tr.org", "TargetService_4130");

    public TargetService4130() {
        super(__getWsdlLocation(), TARGETSERVICE4130_QNAME);
    }

    public TargetService4130(WebServiceFeature... features) {
        super(__getWsdlLocation(), TARGETSERVICE4130_QNAME, features);
    }

    public TargetService4130(URL wsdlLocation) {
        super(wsdlLocation, TARGETSERVICE4130_QNAME);
        TARGETSERVICE4130_WSDL_LOCATION = wsdlLocation;
        TARGETSERVICE4130_EXCEPTION = null;
    }

    public TargetService4130(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TARGETSERVICE4130_QNAME, features);
        TARGETSERVICE4130_WSDL_LOCATION = wsdlLocation;
        TARGETSERVICE4130_EXCEPTION = null;
    }

    public TargetService4130(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
        TARGETSERVICE4130_WSDL_LOCATION = wsdlLocation;
        TARGETSERVICE4130_EXCEPTION = null;
    }

    public TargetService4130(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
        TARGETSERVICE4130_WSDL_LOCATION = wsdlLocation;
        TARGETSERVICE4130_EXCEPTION = null;
    }

    /**
     * 
     * @return
     *     returns TargetServicePortType
     */
    @WebEndpoint(name = "TargetServiceHttpSoap11Endpoint")
    public TargetServicePortType getTargetServiceHttpSoap11Endpoint() {
        return super.getPort(new QName("http://impl.services.service.ws.projectdirector.gs4tr.org", "TargetServiceHttpSoap11Endpoint"), TargetServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TargetServicePortType
     */
    @WebEndpoint(name = "TargetServiceHttpSoap11Endpoint")
    public TargetServicePortType getTargetServiceHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.services.service.ws.projectdirector.gs4tr.org", "TargetServiceHttpSoap11Endpoint"), TargetServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TARGETSERVICE4130_EXCEPTION!= null) {
            throw TARGETSERVICE4130_EXCEPTION;
        }
        return TARGETSERVICE4130_WSDL_LOCATION;
    }

}
