
package org.gs4tr.projectdirector.ws.service.services.impl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.gs4tr.projectdirector.model.dto.xsd.DocumentTicket;
import org.gs4tr.projectdirector.model.dto.xsd.LanguagePhaseInfo;
import org.gs4tr.projectdirector.model.dto.xsd.PagedListInfo;
import org.gs4tr.projectdirector.model.dto.xsd.PreviewResult;
import org.gs4tr.projectdirector.model.dto.xsd.RepositoryItem;
import org.gs4tr.projectdirector.model.dto.xsd.Target;
import org.gs4tr.projectdirector.model.dto.xsd.TargetPagedList;
import org.gs4tr.projectdirector.model.dto.xsd.TargetSearchRequest;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TargetServicePortType", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
@XmlSeeAlso({
    org.gs4tr.projectdirector.model.dto.xsd.ObjectFactory.class,
    org.gs4tr.projectdirector.ws.service.services.impl.ObjectFactory.class,
    org.w3._2005._05.xmlmime.ObjectFactory.class
})
public interface TargetServicePortType {


    /**
     * 
     * @param ticket
     * @return
     *     returns org.gs4tr.projectdirector.model.dto.xsd.Target
     */
    @WebMethod(action = "urn:findByTicket")
    @WebResult(targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
    @RequestWrapper(localName = "findByTicket", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.FindTargetByTicket")
    @ResponseWrapper(localName = "findByTicketResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.FindTargetByTicketResponse")
    public Target findByTicket(
        @WebParam(name = "ticket", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        String ticket);

    /**
     * 
     * @param targetId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:cancelTarget")
    @WebResult(targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
    @RequestWrapper(localName = "cancelTarget", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.CancelTarget")
    @ResponseWrapper(localName = "cancelTargetResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.CancelTargetResponse")
    public String cancelTarget(
        @WebParam(name = "targetId", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        String targetId);

    /**
     * 
     * @param targetLocale
     * @param documentId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:cancelTargetByDocumentId")
    @WebResult(targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
    @RequestWrapper(localName = "cancelTargetByDocumentId", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.CancelTargetByDocumentId")
    @ResponseWrapper(localName = "cancelTargetByDocumentIdResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.CancelTargetByDocumentIdResponse")
    public String cancelTargetByDocumentId(
        @WebParam(name = "documentId", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        DocumentTicket documentId,
        @WebParam(name = "targetLocale", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        String targetLocale);

    /**
     * 
     * @param submissionTickets
     * @param maxResults
     * @return
     *     returns java.util.List<org.gs4tr.projectdirector.model.dto.xsd.Target>
     */
    @WebMethod(action = "urn:getCompletedTargetsBySubmissions")
    @WebResult(targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
    @RequestWrapper(localName = "getCompletedTargetsBySubmissions", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.GetCompletedTargetsBySubmissions")
    @ResponseWrapper(localName = "getCompletedTargetsBySubmissionsResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.GetCompletedTargetsBySubmissionsResponse")
    public List<Target> getCompletedTargetsBySubmissions(
        @WebParam(name = "submissionTickets", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        List<String> submissionTickets,
        @WebParam(name = "maxResults", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        int maxResults);

    /**
     * 
     * @param projectTickets
     * @param maxResults
     * @return
     *     returns java.util.List<org.gs4tr.projectdirector.model.dto.xsd.Target>
     */
    @WebMethod(action = "urn:getCompletedTargetsByProjects")
    @WebResult(targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
    @RequestWrapper(localName = "getCompletedTargetsByProjects", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.GetCompletedTargetsByProjects")
    @ResponseWrapper(localName = "getCompletedTargetsByProjectsResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.GetCompletedTargetsByProjectsResponse")
    public List<Target> getCompletedTargetsByProjects(
        @WebParam(name = "projectTickets", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        List<String> projectTickets,
        @WebParam(name = "maxResults", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        int maxResults);

    /**
     * 
     * @param submissionTicket
     * @param batchName
     * @param targetLanguage
     * @param phaseName
     * @return
     *     returns org.gs4tr.projectdirector.model.dto.xsd.LanguagePhaseInfo
     */
    @WebMethod(action = "urn:getLanguagePhaseInfo")
    @WebResult(targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
    @RequestWrapper(localName = "getLanguagePhaseInfo", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.GetLanguagePhaseInfo")
    @ResponseWrapper(localName = "getLanguagePhaseInfoResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.GetLanguagePhaseInfoResponse")
    public LanguagePhaseInfo getLanguagePhaseInfo(
        @WebParam(name = "submissionTicket", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        String submissionTicket,
        @WebParam(name = "batchName", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        String batchName,
        @WebParam(name = "targetLanguage", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        String targetLanguage,
        @WebParam(name = "phaseName", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        String phaseName);

    /**
     * 
     * @param submissionTickets
     * @param info
     * @return
     *     returns org.gs4tr.projectdirector.model.dto.xsd.TargetPagedList
     */
    @WebMethod(action = "urn:getPagedCompletedTargetsBySubmissions")
    @WebResult(targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
    @RequestWrapper(localName = "getPagedCompletedTargetsBySubmissions", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.GetPagedCompletedTargetsBySubmissions")
    @ResponseWrapper(localName = "getPagedCompletedTargetsBySubmissionsResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.GetPagedCompletedTargetsBySubmissionsResponse")
    public TargetPagedList getPagedCompletedTargetsBySubmissions(
        @WebParam(name = "submissionTickets", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        List<String> submissionTickets,
        @WebParam(name = "info", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        PagedListInfo info);

    /**
     * 
     * @param projectTickets
     * @param info
     * @return
     *     returns org.gs4tr.projectdirector.model.dto.xsd.TargetPagedList
     */
    @WebMethod(action = "urn:getPagedCompletedTargetsByProjects")
    @WebResult(targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
    @RequestWrapper(localName = "getPagedCompletedTargetsByProjects", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.GetPagedCompletedTargetsByProjects")
    @ResponseWrapper(localName = "getPagedCompletedTargetsByProjectsResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.GetPagedCompletedTargetsByProjectsResponse")
    public TargetPagedList getPagedCompletedTargetsByProjects(
        @WebParam(name = "projectTickets", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        List<String> projectTickets,
        @WebParam(name = "info", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        PagedListInfo info);

    /**
     * 
     * @param targetId
     * @return
     *     returns org.gs4tr.projectdirector.model.dto.xsd.RepositoryItem
     */
    @WebMethod(action = "urn:downloadTargetResource")
    @WebResult(targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
    @RequestWrapper(localName = "downloadTargetResource", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.DownloadTargetResource")
    @ResponseWrapper(localName = "downloadTargetResourceResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.DownloadTargetResourceResponse")
    public RepositoryItem downloadTargetResource(
        @WebParam(name = "targetId", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        String targetId);

    /**
     * 
     * @param uuid
     * @return
     *     returns org.gs4tr.projectdirector.model.dto.xsd.PreviewResult
     */
    @WebMethod(action = "urn:downloadTranslationPreview")
    @WebResult(targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
    @RequestWrapper(localName = "downloadTranslationPreview", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.DownloadTranslationPreview")
    @ResponseWrapper(localName = "downloadTranslationPreviewResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.DownloadTranslationPreviewResponse")
    public PreviewResult downloadTranslationPreview(
        @WebParam(name = "uuid", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        String uuid);

    /**
     * 
     * @param targetId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:sendDownloadConfirmation")
    @WebResult(targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
    @RequestWrapper(localName = "sendDownloadConfirmation", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.SendDownloadConfirmation")
    @ResponseWrapper(localName = "sendDownloadConfirmationResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.SendDownloadConfirmationResponse")
    public String sendDownloadConfirmation(
        @WebParam(name = "targetId", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        String targetId);

    /**
     * 
     * @param documentTickets
     * @param maxResults
     * @return
     *     returns java.util.List<org.gs4tr.projectdirector.model.dto.xsd.Target>
     */
    @WebMethod(action = "urn:getCompletedTargetsByDocuments")
    @WebResult(targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
    @RequestWrapper(localName = "getCompletedTargetsByDocuments", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.GetCompletedTargetsByDocuments")
    @ResponseWrapper(localName = "getCompletedTargetsByDocumentsResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.GetCompletedTargetsByDocumentsResponse")
    public List<Target> getCompletedTargetsByDocuments(
        @WebParam(name = "documentTickets", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        List<String> documentTickets,
        @WebParam(name = "maxResults", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        int maxResults);

    /**
     * 
     * @param targetId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:requestTranslationPreview")
    @WebResult(targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
    @RequestWrapper(localName = "requestTranslationPreview", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.RequestTranslationPreview")
    @ResponseWrapper(localName = "requestTranslationPreviewResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.RequestTranslationPreviewResponse")
    public String requestTranslationPreview(
        @WebParam(name = "targetId", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        List<String> targetId);

    /**
     * Deprecated since 4.5.0
     * 
     * @param command
     * @param info
     * @return
     *     returns org.gs4tr.projectdirector.model.dto.xsd.TargetPagedList
     */
    @WebMethod(action = "urn:search")
    @WebResult(targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
    @RequestWrapper(localName = "search", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.SearchTarget")
    @ResponseWrapper(localName = "searchResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.SearchTargetResponse")
    public TargetPagedList search(
        @WebParam(name = "command", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        TargetSearchRequest command,
        @WebParam(name = "info", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        PagedListInfo info);

    /**
     * 
     * @param documentTickets
     * @param info
     * @return
     *     returns java.util.List<org.gs4tr.projectdirector.model.dto.xsd.Target>
     */
    @WebMethod(action = "urn:browseTargetsByDocuments")
    @Action(input = "urn:browseTargetsByDocuments", output = "urn:browseTargetsByDocumentsResponse")
    @RequestWrapper(localName = "browseTargetsByDocuments", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.BrowseTargetsByDocuments")
    @ResponseWrapper(localName = "browseTargetsByDocumentsResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.BrowseTargetsByDocumentsResponse")
    @WebResult(name = "return", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
    public java.util.List<org.gs4tr.projectdirector.model.dto.xsd.Target> browseTargetsByDocuments(
        @WebParam(name = "documentTickets", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        java.util.List<java.lang.String> documentTickets,
        @WebParam(name = "info", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        org.gs4tr.projectdirector.model.dto.xsd.PagedListInfo info
    );

    /**
     * 
     * @param documentTickets
     * @param maxResults
     * @return
     *     returns java.util.List<org.gs4tr.projectdirector.model.dto.xsd.Target>
     */
    @WebMethod(action = "urn:getCanceledTargetsByDocuments")
    @WebResult(targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
    @RequestWrapper(localName = "getCanceledTargetsByDocuments", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.GetCanceledTargetsByDocuments")
    @ResponseWrapper(localName = "getCanceledTargetsByDocumentsResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.GetCanceledTargetsByDocumentsResponse")
    public List<Target> getCanceledTargetsByDocuments(
        @WebParam(name = "documentTickets", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        List<String> documentTickets,
        @WebParam(name = "maxResults", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        int maxResults);

    /**
     * 
     * @param projectTickets
     * @param maxResults
     * @return
     *     returns java.util.List<org.gs4tr.projectdirector.model.dto.xsd.Target>
     */
    @WebMethod(action = "urn:getCanceledTargetsByProjects")
    @WebResult(targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
    @RequestWrapper(localName = "getCanceledTargetsByProjects", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.GetCanceledTargetsByProjects")
    @ResponseWrapper(localName = "getCanceledTargetsByProjectsResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.GetCanceledTargetsByProjectsResponse")
    public List<Target> getCanceledTargetsByProjects(
        @WebParam(name = "projectTickets", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        List<String> projectTickets,
        @WebParam(name = "maxResults", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        int maxResults);

    /**
     * 
     * @param submissionTickets
     * @param maxResults
     * @return
     *     returns java.util.List<org.gs4tr.projectdirector.model.dto.xsd.Target>
     */
    @WebMethod(action = "urn:getCanceledTargetsBySubmissions")
    @WebResult(targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
    @RequestWrapper(localName = "getCanceledTargetsBySubmissions", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.GetCanceledTargetsBySubmissions")
    @ResponseWrapper(localName = "getCanceledTargetsBySubmissionsResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.GetCanceledTargetsBySubmissionsResponse")
    public List<Target> getCanceledTargetsBySubmissions(
        @WebParam(name = "submissionTickets", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        List<String> submissionTickets,
        @WebParam(name = "maxResults", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        int maxResults);

}
