package org.gs4tr.projectdirector.ws.service.services.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2016-05-25T10:52:05.952+03:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", name = "TargetServicePortType")
@XmlSeeAlso({ObjectFactory.class, org.gs4tr.projectdirector.model.dto.ObjectFactory.class, org.w3._2005._05.xmlmime.ObjectFactory.class})
public interface TargetServicePortType {

    @WebMethod(action = "urn:getCanceledTargetsByProjects")
    @Action(input = "urn:getCanceledTargetsByProjects", output = "urn:getCanceledTargetsByProjectsResponse")
    @RequestWrapper(localName = "getCanceledTargetsByProjects", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.GetCanceledTargetsByProjects")
    @ResponseWrapper(localName = "getCanceledTargetsByProjectsResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.GetCanceledTargetsByProjectsResponse")
    @WebResult(name = "return", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
    public java.util.List<org.gs4tr.projectdirector.model.dto.Target> getCanceledTargetsByProjects(
        @WebParam(name = "projectTickets", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        java.util.List<java.lang.String> projectTickets,
        @WebParam(name = "maxResults", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        int maxResults
    );

    @WebMethod(action = "urn:cancelTargetByDocumentId")
    @Action(input = "urn:cancelTargetByDocumentId", output = "urn:cancelTargetByDocumentIdResponse")
    @RequestWrapper(localName = "cancelTargetByDocumentId", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.CancelTargetByDocumentId")
    @ResponseWrapper(localName = "cancelTargetByDocumentIdResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.CancelTargetByDocumentIdResponse")
    @WebResult(name = "return", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
    public java.lang.String cancelTargetByDocumentId(
        @WebParam(name = "documentId", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        org.gs4tr.projectdirector.model.dto.DocumentTicket documentId,
        @WebParam(name = "targetLocale", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        java.lang.String targetLocale
    );

    @WebMethod(action = "urn:getPagedCompletedTargetsBySubmissions")
    @Action(input = "urn:getPagedCompletedTargetsBySubmissions", output = "urn:getPagedCompletedTargetsBySubmissionsResponse")
    @RequestWrapper(localName = "getPagedCompletedTargetsBySubmissions", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.GetPagedCompletedTargetsBySubmissions")
    @ResponseWrapper(localName = "getPagedCompletedTargetsBySubmissionsResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.GetPagedCompletedTargetsBySubmissionsResponse")
    @WebResult(name = "return", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
    public org.gs4tr.projectdirector.model.dto.TargetPagedList getPagedCompletedTargetsBySubmissions(
        @WebParam(name = "submissionTickets", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        java.util.List<java.lang.String> submissionTickets,
        @WebParam(name = "info", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        org.gs4tr.projectdirector.model.dto.PagedListInfo info
    );

    @WebMethod(action = "urn:getCanceledTargetsBySubmissions")
    @Action(input = "urn:getCanceledTargetsBySubmissions", output = "urn:getCanceledTargetsBySubmissionsResponse")
    @RequestWrapper(localName = "getCanceledTargetsBySubmissions", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.GetCanceledTargetsBySubmissions")
    @ResponseWrapper(localName = "getCanceledTargetsBySubmissionsResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.GetCanceledTargetsBySubmissionsResponse")
    @WebResult(name = "return", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
    public java.util.List<org.gs4tr.projectdirector.model.dto.Target> getCanceledTargetsBySubmissions(
        @WebParam(name = "submissionTickets", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        java.util.List<java.lang.String> submissionTickets,
        @WebParam(name = "maxResults", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        int maxResults
    );

    @WebMethod(action = "urn:downloadTranslationPreview")
    @Action(input = "urn:downloadTranslationPreview", output = "urn:downloadTranslationPreviewResponse")
    @RequestWrapper(localName = "downloadTranslationPreview", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.DownloadTranslationPreview")
    @ResponseWrapper(localName = "downloadTranslationPreviewResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.DownloadTranslationPreviewResponse")
    @WebResult(name = "return", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
    public org.gs4tr.projectdirector.model.dto.PreviewResult downloadTranslationPreview(
        @WebParam(name = "uuid", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        java.lang.String uuid
    );

    @WebMethod(action = "urn:getCompletedTargetsByProjects")
    @Action(input = "urn:getCompletedTargetsByProjects", output = "urn:getCompletedTargetsByProjectsResponse")
    @RequestWrapper(localName = "getCompletedTargetsByProjects", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.GetCompletedTargetsByProjects")
    @ResponseWrapper(localName = "getCompletedTargetsByProjectsResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.GetCompletedTargetsByProjectsResponse")
    @WebResult(name = "return", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
    public java.util.List<org.gs4tr.projectdirector.model.dto.Target> getCompletedTargetsByProjects(
        @WebParam(name = "projectTickets", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        java.util.List<java.lang.String> projectTickets,
        @WebParam(name = "maxResults", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        int maxResults
    );

    @WebMethod(action = "urn:getCompletedTargetsBySubmissions")
    @Action(input = "urn:getCompletedTargetsBySubmissions", output = "urn:getCompletedTargetsBySubmissionsResponse")
    @RequestWrapper(localName = "getCompletedTargetsBySubmissions", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.GetCompletedTargetsBySubmissions")
    @ResponseWrapper(localName = "getCompletedTargetsBySubmissionsResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.GetCompletedTargetsBySubmissionsResponse")
    @WebResult(name = "return", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
    public java.util.List<org.gs4tr.projectdirector.model.dto.Target> getCompletedTargetsBySubmissions(
        @WebParam(name = "submissionTickets", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        java.util.List<java.lang.String> submissionTickets,
        @WebParam(name = "maxResults", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        int maxResults
    );

    @WebMethod(action = "urn:getPagedCompletedTargetsByProjects")
    @Action(input = "urn:getPagedCompletedTargetsByProjects", output = "urn:getPagedCompletedTargetsByProjectsResponse")
    @RequestWrapper(localName = "getPagedCompletedTargetsByProjects", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.GetPagedCompletedTargetsByProjects")
    @ResponseWrapper(localName = "getPagedCompletedTargetsByProjectsResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.GetPagedCompletedTargetsByProjectsResponse")
    @WebResult(name = "return", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
    public org.gs4tr.projectdirector.model.dto.TargetPagedList getPagedCompletedTargetsByProjects(
        @WebParam(name = "projectTickets", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        java.util.List<java.lang.String> projectTickets,
        @WebParam(name = "info", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        org.gs4tr.projectdirector.model.dto.PagedListInfo info
    );

    @WebMethod(action = "urn:sendDownloadConfirmation")
    @Action(input = "urn:sendDownloadConfirmation", output = "urn:sendDownloadConfirmationResponse")
    @RequestWrapper(localName = "sendDownloadConfirmation", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.SendDownloadConfirmation")
    @ResponseWrapper(localName = "sendDownloadConfirmationResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.SendDownloadConfirmationResponse")
    @WebResult(name = "return", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
    public java.lang.String sendDownloadConfirmation(
        @WebParam(name = "targetId", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        java.lang.String targetId
    );

    @WebMethod(action = "urn:cancelTarget")
    @Action(input = "urn:cancelTarget", output = "urn:cancelTargetResponse")
    @RequestWrapper(localName = "cancelTarget", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.CancelTarget")
    @ResponseWrapper(localName = "cancelTargetResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.CancelTargetResponse")
    @WebResult(name = "return", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
    public java.lang.String cancelTarget(
        @WebParam(name = "targetId", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        java.lang.String targetId
    );

    @WebMethod(action = "urn:findByTicket")
    @Action(input = "urn:findByTicket", output = "urn:findByTicketResponse")
    @RequestWrapper(localName = "findByTicket", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.FindTargetByTicket")
    @ResponseWrapper(localName = "findByTicketResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.FindTargetByTicketResponse")
    @WebResult(name = "return", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
    public org.gs4tr.projectdirector.model.dto.Target findByTicket(
        @WebParam(name = "ticket", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        java.lang.String ticket
    );

    /**
     * Deprecated since 4.5.0
     */
    @WebMethod(action = "urn:search")
    @Action(input = "urn:search", output = "urn:searchResponse")
    @RequestWrapper(localName = "search", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.SearchTarget")
    @ResponseWrapper(localName = "searchResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.SearchTargetResponse")
    @WebResult(name = "return", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
    public org.gs4tr.projectdirector.model.dto.TargetPagedList search(
        @WebParam(name = "command", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        org.gs4tr.projectdirector.model.dto.TargetSearchRequest command,
        @WebParam(name = "info", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        org.gs4tr.projectdirector.model.dto.PagedListInfo info
    );

    @WebMethod(action = "urn:downloadTargetResource")
    @Action(input = "urn:downloadTargetResource", output = "urn:downloadTargetResourceResponse")
    @RequestWrapper(localName = "downloadTargetResource", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.DownloadTargetResource")
    @ResponseWrapper(localName = "downloadTargetResourceResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.DownloadTargetResourceResponse")
    @WebResult(name = "return", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
    public org.gs4tr.projectdirector.model.dto.RepositoryItem downloadTargetResource(
        @WebParam(name = "targetId", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        java.lang.String targetId
    );

    @WebMethod(action = "urn:requestTranslationPreview")
    @Action(input = "urn:requestTranslationPreview", output = "urn:requestTranslationPreviewResponse")
    @RequestWrapper(localName = "requestTranslationPreview", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.RequestTranslationPreview")
    @ResponseWrapper(localName = "requestTranslationPreviewResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.RequestTranslationPreviewResponse")
    @WebResult(name = "return", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
    public java.lang.String requestTranslationPreview(
        @WebParam(name = "targetId", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        java.util.List<java.lang.String> targetId
    );

    @WebMethod(action = "urn:getCanceledTargetsByDocuments")
    @Action(input = "urn:getCanceledTargetsByDocuments", output = "urn:getCanceledTargetsByDocumentsResponse")
    @RequestWrapper(localName = "getCanceledTargetsByDocuments", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.GetCanceledTargetsByDocuments")
    @ResponseWrapper(localName = "getCanceledTargetsByDocumentsResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.GetCanceledTargetsByDocumentsResponse")
    @WebResult(name = "return", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
    public java.util.List<org.gs4tr.projectdirector.model.dto.Target> getCanceledTargetsByDocuments(
        @WebParam(name = "documentTickets", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        java.util.List<java.lang.String> documentTickets,
        @WebParam(name = "maxResults", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        int maxResults
    );

    @WebMethod(action = "urn:browseTargetsByDocuments")
    @Action(input = "urn:browseTargetsByDocuments", output = "urn:browseTargetsByDocumentsResponse")
    @RequestWrapper(localName = "browseTargetsByDocuments", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.BrowseTargetsByDocuments")
    @ResponseWrapper(localName = "browseTargetsByDocumentsResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.BrowseTargetsByDocumentsResponse")
    @WebResult(name = "return", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
    public java.util.List<org.gs4tr.projectdirector.model.dto.Target> browseTargetsByDocuments(
        @WebParam(name = "documentTickets", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        java.util.List<java.lang.String> documentTickets,
        @WebParam(name = "info", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        org.gs4tr.projectdirector.model.dto.PagedListInfo info
    );

    @WebMethod(action = "urn:getCompletedTargetsByDocuments")
    @Action(input = "urn:getCompletedTargetsByDocuments", output = "urn:getCompletedTargetsByDocumentsResponse")
    @RequestWrapper(localName = "getCompletedTargetsByDocuments", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.GetCompletedTargetsByDocuments")
    @ResponseWrapper(localName = "getCompletedTargetsByDocumentsResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.GetCompletedTargetsByDocumentsResponse")
    @WebResult(name = "return", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
    public java.util.List<org.gs4tr.projectdirector.model.dto.Target> getCompletedTargetsByDocuments(
        @WebParam(name = "documentTickets", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        java.util.List<java.lang.String> documentTickets,
        @WebParam(name = "maxResults", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        int maxResults
    );
}
