
package org.gs4tr.projectdirector.ws.service.services.impl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.gs4tr.projectdirector.model.dto.xsd.Language;
import org.gs4tr.projectdirector.model.dto.xsd.TiUserInfo;
import org.gs4tr.projectdirector.model.dto.xsd.UserInfo;
import org.gs4tr.projectdirector.model.dto.xsd.UserProfile;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserProfileServicePortType", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
@XmlSeeAlso({
    org.gs4tr.projectdirector.model.dto.xsd.ObjectFactory.class,
    org.gs4tr.projectdirector.ws.service.services.impl.ObjectFactory.class,
    org.w3._2005._05.xmlmime.ObjectFactory.class
})
public interface UserProfileServicePortType {


    /**
     * 
     * @param projectShortCode
     * @return
     *     returns java.util.List<org.gs4tr.projectdirector.model.dto.xsd.UserProfile>
     */
    @WebMethod(action = "urn:getSubmitters")
    @WebResult(targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
    @RequestWrapper(localName = "getSubmitters", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.GetSubmitters")
    @ResponseWrapper(localName = "getSubmittersResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.GetSubmittersResponse")
    public List<UserProfile> getSubmitters(
        @WebParam(name = "projectShortCode", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        String projectShortCode);

    /**
     * Deprecated since 4.5.0
     * 
     * @param tiUserInfo
     * @param userInfo
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod(action = "urn:createUser")
    @WebResult(targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
    @RequestWrapper(localName = "createUser", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.CreateUser")
    @ResponseWrapper(localName = "createUserResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.CreateUserResponse")
    public List<String> createUser(
        @WebParam(name = "userInfo", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        UserInfo userInfo,
        @WebParam(name = "tiUserInfo", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        TiUserInfo tiUserInfo);

    /**
     * 
     * @param ticket
     * @return
     *     returns org.gs4tr.projectdirector.model.dto.xsd.UserProfile
     */
    @WebMethod(action = "urn:findByTicket")
    @WebResult(targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
    @RequestWrapper(localName = "findByTicket", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.FindUserByTicket")
    @ResponseWrapper(localName = "findByTicketResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.FindUserByTicketResponse")
    public UserProfile findByTicket(
        @WebParam(name = "ticket", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        String ticket);

    /**
     * 
     * @return
     *     returns org.gs4tr.projectdirector.ws.service.services.impl.GetCurrentUserLanguagesResponse
     */
    @WebMethod(action = "urn:getCurrentUserLanguages")
    @WebResult(name = "getCurrentUserLanguagesResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GetCurrentUserLanguagesResponse getCurrentUserLanguages();

    /**
     * 
     * @param userTicket
     * @return
     *     returns java.util.List<org.gs4tr.projectdirector.model.dto.xsd.Language>
     */
    @WebMethod(action = "urn:getUserLanguages")
    @WebResult(targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
    @RequestWrapper(localName = "getUserLanguages", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.GetUserLanguages")
    @ResponseWrapper(localName = "getUserLanguagesResponse", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org", className = "org.gs4tr.projectdirector.ws.service.services.impl.GetUserLanguagesResponse")
    public List<Language> getUserLanguages(
        @WebParam(name = "userTicket", targetNamespace = "http://impl.services.service.ws.projectdirector.gs4tr.org")
        String userTicket);

}
